# This is copied from github-reusable-workflows/.github/workflows/reusable-workflow-tag-and-release-terraform-module.yaml
#
# This is the workflow for distribution to repositories across the organization.
# It will call the reusable Tag and Release Terraform Module workflow,
# which will create a new tag based on a value in version file and create a GitHub release.
---
name: ğŸ· Tag and Release Terraform Module

on:
  workflow_call:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check out code
        uses: actions/checkout@v3

      - name: ğŸ· Create a tag
        id: create-tag
        uses: butlerlogic/action-autotag@stable
        with:
          strategy: regex
          root: "version"
          regex_pattern: "(\\d+\\.\\d+\\.\\d+)"
          tag_prefix: "v"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: ğŸ¦„ Create a release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ steps.create-tag.outputs.tagname }}
          token: ${{ secrets.GITHUB_TOKEN }}